dataset:
  lookback_window: 24
  forecast_horizon: 3
  shift: 1

data:
  feature_columns:
    - workingday
    - temp
    - hum
    - day_sin
    - day_cos
    - week_sin
    - week_cos
    - casual_s
    - registered_s
  target_columns:
    - casual_s
    - registered_s

model:
  batch_size: 64
  num_features: 9
  num_targets: 2